workflow: update dependenices improvement

diff --git a/.github/workflows/dependencies-update.yaml b/.github/workflows/dependencies-update.yaml
--- a/.github/workflows/dependencies-update.yaml
+++ b/.github/workflows/dependencies-update.yaml
@@ -1,38 +1,49 @@
 on: 
-  schedule:
-    - cron: '0 12 * * *'
+  #schedule:
+    #- cron: '0 12 * * *'
+  push:
+    branch:
+      - workflow
 
 jobs:
   createPullRequest:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-        with:
-          ref: master
 
       - name: Set up Go
         uses: actions/setup-go@v2.1.3
         with:
           go-version: 1.16
-        id: go
 
-      - name: Update dependencies
+      - name: Update dependencies # updates go depenencies, saves output
+        id: update
+        continue-on-error: true
+        shell: bash -E {0} # we don't need -e (pipefile) option (disturbs)
         run: |
-          go get -u ./...
+          go get -u ./... &>> /tmp/output.txt
+          echo "update-success=$?" >> $GITHUB_ENV # saves exit code
           go mod tidy
+          echo 'diffs<<EOF' >> $GITHUB_ENV
+          cat /tmp/output.txt >> $GITHUB_ENV
+          echo 'EOF' >> $GITHUB_ENV
 
-      - name: Create commits
-        run: |
-          git config user.name ${{ github.actor }}
-          git config user.email ${{ github.actor }}@users.noreply.github.com
-          git fetch origin
-          git add .
-          if [[ $(git diff --stat) != '' ]]; then
-            git commit -am "all: dependencies update"
-          else
-            echo "clean - nothing to commit"
-          fi
-      - name: Create Pull Request
+      - if: env.update-success > 0
+        name: open issue
+        uses: alialaa/issue-action@v1
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          title: "Error updating dependencies!"
+          body: |
+            Hi there!
+            GitHub action found an issues while updating golang dependencies.
+            the full stack trace is here:
+            ```
+            ${{ env.diffs }}
+            ```
+
+      - if: env.update-success == 0
+        name: Create Pull Request
         id: cpr
         uses: peter-evans/create-pull-request@v3
         with:
@@ -44,5 +55,10 @@ jobs:
           branch: dependencies-update
           delete-branch: true
           title: 'update golang dependencies'
-          body: ""
+          body: |
+            "Automatic GitHub action updates the following dependencies:"
+            ```
+            ${{ env.diffs }}
+            ```
           draft: false
+
